version: '3.5'

services:
  orm_example_postgres:
    container_name: orm_example_postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres_orm_example:/data/postgres
    ports:
      - 5435:5432
    restart: unless-stopped
  
  orm_example_pgadmin:
    container_name: orm_example_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_orm_example:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped


volumes:
    postgres_orm_example:
    pgadmin_orm_example: